version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      next-ecosystem:
        patterns:
          - "next"
          - "next-intl"
          - "react"
          - "react-dom"
          - "@types/react*"
      content-collections:
        patterns:
          - "@content-collections/*"
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
      vercel:
        patterns:
          - "@vercel/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
