name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger the workflow on push events to the master branch.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment.

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensures you fetch all history for .git-based commands to work.

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.3.0'  # Specify the Node.js version.

    - name: Install dependencies

      run: npm install  # Install project dependencies.

    - name: Build
      run: npm run build  # Build the project and output to 'build' directory.

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.6.1
      with:
        token: ${{ secrets.PAT_TOKEN }} # Use the PAT token to authenticate the deployment
        repository-name: lsiem.github.io # Deploy to the lsiem.github.io repository
        branch: main # The branch the action should deploy to.
        folder: build # The folder the action should deploy.
        clean: true # Automatically remove deleted files from the deployment.


