name: Build and Deploy to GitHub Pages

on: [push]

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest  # Specifies the runner environment.

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v4
    
    - name: Install and build
      run: |
        npm ci
        npm run build
      
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.6.9
      with:
        token: ${{ secrets.PAT_TOKEN }} # Use the PAT token to authenticate the deployment
        repository-name: lsiem/lsiem.github.io # Deploy to the lsiem.github.io repository
        branch: main # The branch the action should deploy to.
        folder: build # The folder the action should deploy.
        clean: true # Automatically remove deleted files from the deployment.


